image: registry.znuny.com/znuny/docker-otrs6ci:latest

services:
  - mysql:latest

variables:
  MYSQL_DATABASE: otrs
  MYSQL_ROOT_PASSWORD: znuny4otrs

stages:
  - test
  - deploy

job_test_otrs_Znuny4OTRSSortByLastContact:
  stage: test
  script:
    - su -c "perl /opt/otrs/bin/otrs.Console.pl Dev::UnitTest::Run --verbose --test scripts/test/Ticket/Event/Znuny4OTRSSortByLastContact" -s /bin/bash otrs#

job_deploy_otrs_Znuny4OTRSSortByLastContact:
  stage: deploy
  script:
    - sh /sync_repo.sh git@github.com:znuny/Znuny4OTRS-SortByLastContact.git