image: registry.znuny.com/znuny/docker-otrs4ci:latest
## nofilter(TidyAll::Plugin::OTRS::Znuny4OTRS::Gitlabci::Image)

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - sh /sync_repo.sh git@github.com:znuny/Znuny4OTRS-SortByLastContact.git